---
title: "Evaluating Linkage Results"
format: gfm
editor: visual
---

## Assumptions

`tar_make()` has been successfully run

```{r}
library('data.table',quietly = TRUE, verbose = FALSE)
library('DBI')
library('glue')
library('targets')
library('ggplot2')
library('plotly')
tar_source()
```

## Fit Metrics

## Review Clusters Metrics

```{r}
summ = setDT(arrow::read_parquet(tar_read(components)[2]))
setorder(summ, +final_density)

# Clusters that are large and low density
knitr::kable(head(summ[final_size > 10]))

# High density clusters
knitr::kable(tail(summ[final_size > 10]))
```

```{r visnetwork}

# Get a cluster's details
net = retrieve_network_info(net_id_val = '1_2',
                      net_id_col = DBI::Id(column = 'final_comp_id'),
                      net_tab = tar_read(components)[1],
                      result_tab = unlist(c(tar_read(preds), tar_read(fixed))),
                      cutpoint = tar_read(cutme)[1], 
                      identifier_tab = tar_read(data))

vis = vis_network(
  net$nodes, 
  net$edge, 
  tooltip_cols = c('first_name_noblank', 'last_name_noblank', 
                   'dob_clean', 'clean_hash'),
  labels = 'final_comp_id',
  return_data = T)

plot(vis[[1]])

```
