---
title: "Readme"
format: gfm
editor: visual
---

This repository (and its parent, the `hyrule` package) contains code, instructions, and commentary on record linkage (also known as entity resolution) using ensemble machine learning implemented in R.

There are three main vignettes/examples:

1.  [Record Linkage Pipeline](_targets.md): A mostly comprehensive example of a `targets` analysis pipeline for machine learning record linkage. The [origin \_targets.qmd](_targets.qmd) file uses targets-flavored markdown and can be edited (or stripped for parts) into a record linkage pipeline using "real" data. To "recreate" the document users must first render the .qmd file, execute the pipeline via `tar_make()`, and re-render the .qmd file. The double render is required to populate the parts of the document that rely on completed results.
2.  Musings on evaluating results: Opinions and ideas on how to tell if a record linkage is any good
3.  Generating new training data: A description of some ways to generate effective training data.
